############################
#       by NonKungCH       #
# --- RealCarry Config --- #
############################

# Slowness level applied while carrying (0 = Slowness 1, 1 = Slowness 2)
slowness-level: 0

# Messages
messages:
  plugin-reloaded: "&aRealCarry config has been reloaded!"
  no-permission: "&cYou don't have permission to use this command."
  carrying-block: "&aYou picked up %block%!"
  carrying-entity: "&aYou picked up %entity%!"
  placed-object: "&eYou have placed the carried object!"
  already-carrying: "&cYou are already carrying something!"