############################################################
#                    RealCarry Config                      #
############################################################

slowness-level: 0

# รายชื่อ Entity ที่ "ห้าม" อุ้ม (Blacklist)
forbidden-mobs:
  - WITHER
  - ENDER_DRAGON
  - WARDEN
  - ELDER_GUARDIAN

offsets:
  block:
    x: 0.0
    y: 1.2
    z: 1.0
  player:
    x: 0.0
    y: 1.2
    z: 1.2
  mob:
    x: 0.0
    y: 1.2
    z: 1.2

messages:
  plugin-reloaded: "&aRealCarry config has been reloaded!"
  no-permission: "&cYou don't have permission!"
  carrying-block: "&aYou picked up %block%!"
  carrying-entity: "&aYou picked up %entity%!"
  placed-object: "&eYou have placed the object!"
  already-carrying: "&cYou are already carrying something!"
  cannot-carry: "&cYou cannot carry this type of entity! / คุณไม่สามารถอุ้มสิ่งนี้ได้"
